baseURL = "https://eksctl.io"
languageCode = "en-us"
title = "Eksctl"
theme = "eksctl"


[params]
  repository = "weaveworks/eksctl"
  brand_color= "amber-400"
  by_weaveworks = true

[params.twitter]
    username = "weaveworks"
[params.author]
    twitter= "weaveworks"
