version: 2
jobs:
  make-release:
    machine: true
    steps:
      - checkout
      - run: make release

workflows:
  version: 2
  any-commit:
    jobs:
      - make-release:
          requires: [make-eksctl-image]
          filters:
            branches:
              ignore: /.*/
            tags:
              ignore: /^latest_release$/
  release:
    jobs:
      - make-release:
          requires: [make-eksctl-image]
          filters:
            branches:
              ignore: /.*/
            tags:
              ignore: /^latest_release$/
